image: atlassian/default-image:5

pipelines:
  branches:
    unikove-test-front-end:
      - step:
          name: Deploy Frontend TEST
          deployment: unikove
          script:
            - apt-get update && apt-get install -y rsync openssh-client gettext-base
            - find $BITBUCKET_CLONE_DIR -type d -exec chmod 755 {} \;
            - find $BITBUCKET_CLONE_DIR -type f -exec chmod 644 {} \;
            - npm install
            - npm run build
            - rsync -avz --delete --exclude='.git*' --exclude='bitbucket*' $BITBUCKET_CLONE_DIR/dist/ $SSH_USER@$VM_IP:$REMOTE_PATH/

    qa:
      - step:
          name: Deploy Frontend QA
          deployment: qa
          script:
            - apt-get update && apt-get install -y rsync openssh-client gettext-base
            - find $BITBUCKET_CLONE_DIR -type d -exec chmod 755 {} \;
            - find $BITBUCKET_CLONE_DIR -type f -exec chmod 644 {} \;
            - npm install
            - envsubst < env.template > .env
            - npm run build
            - rsync -avz --delete --exclude='.git*' --exclude='bitbucket*' $BITBUCKET_CLONE_DIR/dist/ $SSH_USER@$VM_IP:$REMOTE_PATH/